name: energy-storage-bidding
channels:
    - conda-forge
dependencies:
    - ipykernel
    - numpy
    - pandas 
    - scipy
    - matplotlib
    - pyomo
    - ipopt
    - glpk
    - numba 
    - seaborn